# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-agent-web-test-centralus

on:
  push:
    branches:
      - main
    paths:
    - web/**
  workflow_dispatch:

jobs:
  build:
    defaults:
        run:
          working-directory: web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_API_HOST: "https://app-agent-api-test-centralus.azurewebsites.net"
          fail_on_empty: true
          file_name: .env

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test:ci --if-present
        env:
          CI: ""

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            web/release.zip
            !web/node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52A17DB978D740229D5FAAB25E4D6B68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40EB04C44E374A93886F89A5F0EA9ACF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_233703A97BCA4AEF8FAFD49E39CD30FC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-agent-web-test-centralus'
          package: ./build
          
